### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'string'

### ISSUE THREAD

**Issue by SimonBard** [LilaQ/MCC_Serve#3]
**Describe the bug**
# trying to add Schokoladen-Gugelhupf  (TM) - (2101122)...
# ... done !
# Synching TM from ./tm/ folder : Traceback (most recent call last):
  File "mcc_update.py", line 62, in <module>
    res = mcc_sync_tm()
  File "/home/simon/Downloads/MCC_Serve/lib/mcc_sync.py", line 446, in mcc_sync_tm
    j = json.loads(script.string)
AttributeError: 'NoneType' object has no attribute 'string'

**To Reproduce**
1. Run  python3 mcc_update.py
2. Import recipes from TM folder

**Expected behavior**
Finish import successfully

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Version a92bf34

**Comment by LilaQ** [comment]
Can you check if you have 0kb .html files in your `./tm` directory? Or files smaller than 60k?
